"""
Django settings for examsite project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-dev-key")

# Mặc định bật DEBUG khi dev/local (có thể override bằng biến môi trường)
DEBUG = os.environ.get("DEBUG", "1") == "1"

# Không ép Django nghĩ là đang chạy qua HTTPS proxy khi bạn truy cập trực tiếp IP:8000
SECURE_PROXY_SSL_HEADER = None

# Dev/local dùng HTTP nên KHÔNG dùng secure cookies
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Cho phép truy cập từ localhost và IP máy bạn trong LAN
ALLOWED_HOSTS = [
    "*",
    "localhost",
    "127.0.0.1",
    "192.168.1.3",
]

# Các origin được tin cậy cho CSRF (LAN + ngrok)
CSRF_TRUSTED_ORIGINS = [
    "http://192.168.1.3:8000",
    "http://192.168.1.3",
    "http://localhost:8000",
    "https://trish-unconceited-janine.ngrok-free.dev",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',  # thêm app core
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'examsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # expose judge/session role info to templates
                'core.context_processors.judge_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'examsite.wsgi.application'


CSRF_TRUSTED_ORIGINS = [
    "https://trish-unconceited-janine.ngrok-free.dev",
]
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.environ.get("POSTGRES_DB", "examdb"),
#         "USER": os.environ.get("POSTGRES_USER", "examuser"),
#         "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "examsecret"),
#         "HOST": os.environ.get("DB_HOST", "db"),
#         "PORT": os.environ.get("DB_PORT", "5432"),
#         "CONN_MAX_AGE": 60,
#     }
#     "default": dj_database_url.config(
#         default=os.getenv("DATABASE_URL"),
#         conn_max_age=600,
#         ssl_require=True
#     )
# }

# Prefer DATABASE_URL; if missing, build from individual envs
db_url = os.getenv("DATABASE_URL")
if not db_url:
    db_url = (
        f"postgresql://{os.getenv('POSTGRES_USER','examuser')}:"
        f"{os.getenv('POSTGRES_PASSWORD','examsecret')}@"
        f"{os.getenv('DB_HOST','exam_db')}:"
        f"{os.getenv('DB_PORT','5432')}/"
        f"{os.getenv('POSTGRES_DB','examdb')}"
    )

DATABASES = {
    "default": dj_database_url.parse(
        db_url,
        conn_max_age=600,
        ssl_require=False  # local docker postgres doesn't use SSL
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get("TIME_ZONE", "Asia/Ho_Chi_Minh")
USE_TZ = True

USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")