# Generated by Django 5.2.9 on 2025-12-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieuchamdiem',
            name='diem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
