# Generated by Django 5.2.9 on 2025-12-08 02:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGDScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bgd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.bangiamdoc')),
                ('cuocThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgd_scores', to='core.cuocthi')),
                ('thiSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgd_scores', to='core.thisinh')),
            ],
            options={
                'unique_together': {('bgd', 'cuocThi', 'thiSinh')},
            },
        ),
    ]
