# Generated by Django 5.2.9 on 2025-12-08 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bgdscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgdscore',
            name='diem',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
