# Generated by Django 5.1.14 on 2025-12-11 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_phieuchamdiem_diem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThiSinhVoting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cuocThi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_candidates",
                        to="core.cuocthi",
                    ),
                ),
                (
                    "thiSinh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_voting",
                        to="core.thisinh",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cuocThi"], name="core_thisin_cuocThi_088650_idx"
                    ),
                    models.Index(
                        fields=["thiSinh", "cuocThi"],
                        name="core_thisin_thiSinh_25f1ed_idx",
                    ),
                ],
                "unique_together": {("thiSinh", "cuocThi")},
            },
        ),
        migrations.CreateModel(
            name="VotingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voter_email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("thiSinh_ma", models.CharField(db_index=True, max_length=20)),
                ("thiSinh_ten", models.CharField(max_length=255)),
                ("count", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cuocThi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.cuocthi",
                    ),
                ),
                (
                    "thiSinh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.thisinh"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["thiSinh_ma"], name="core_voting_thiSinh_5fa425_idx"
                    )
                ],
            },
        ),
    ]
