# Generated by Django 5.2.8 on 2025-11-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_battlevote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlevote',
            name='heart',
            field=models.BooleanField(db_index=True, default=False, help_text='Ưu tiên (♥) của giám khảo'),
        ),
    ]
