# Generated by Django 5.2.9 on 2025-12-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bgdscore_diem'),
    ]

    operations = [
        migrations.AddField(
            model_name='vongthi',
            name='bgd_top_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Số lượng Top X sẽ lấy từ vòng trước (ví dụ 10, 5...).', null=True),
        ),
        migrations.AddField(
            model_name='vongthi',
            name='is_bgd_round',
            field=models.BooleanField(default=False, help_text='Nếu bật, vòng này dùng để chọn Top X cho Ban Giám Đốc chấm.'),
        ),
    ]
