# Generated by Django 5.2.9 on 2025-12-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_battlevote_heart'),
    ]

    operations = [
        migrations.AddField(
            model_name='vongthi',
            name='is_special_bonus_round',
            field=models.BooleanField(default=False, help_text='Bật vòng thi đặc biệt (top 20 đấu cặp, chấm 100/0, điểm mẫu chỉ lưu log)'),
        ),
    ]
