# Generated by Django 5.2.9 on 2025-12-10 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vongthi_bgd_top_limit_vongthi_is_bgd_round'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bgdscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bgdscore',
            name='vongThi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bgd_scores', to='core.vongthi'),
        ),
        migrations.AlterField(
            model_name='vongthi',
            name='is_bgd_round',
            field=models.BooleanField(default=False, help_text='Nếu bật, vòng này dùng để chọn Top X thí sinh đưa sang trang BGD GO.'),
        ),
        migrations.AlterUniqueTogether(
            name='bgdscore',
            unique_together={('bgd', 'cuocThi', 'vongThi', 'thiSinh')},
        ),
    ]
