# Generated by Django 5.2.9 on 2025-12-04 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vongthi_is_special_bonus_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCompareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.FloatField(default=0)),
                ('raw_time', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baiThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baithi')),
                ('capThiDau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.capthidau')),
                ('cuocThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuocthi')),
                ('giamKhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.giamkhao')),
                ('thiSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thisinh')),
                ('vongThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vongthi')),
            ],
            options={
                'unique_together': {('capThiDau', 'baiThi', 'giamKhao', 'thiSinh')},
            },
        ),
    ]
