# Generated by Django 5.2.9 on 2025-12-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bonuscomparelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vongthi',
            name='is_special_bonus_round',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SpecialRoundPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuocThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuocthi')),
                ('vongThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vongthi')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bonuscomparelog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bonuscomparelog',
            name='special_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.specialroundpair'),
        ),
        migrations.AlterUniqueTogether(
            name='bonuscomparelog',
            unique_together={('special_pair', 'baiThi', 'giamKhao', 'thiSinh')},
        ),
        migrations.RemoveField(
            model_name='bonuscomparelog',
            name='capThiDau',
        ),
        migrations.CreateModel(
            name='SpecialRoundPairMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=1)),
                ('slot', models.PositiveSmallIntegerField()),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.specialroundpair')),
                ('thiSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thisinh')),
            ],
            options={
                'unique_together': {('pair', 'slot')},
            },
        ),
    ]
